export const CURRENCY_CODES = [
    "INR",
    "USD",
    "AFN",
    "ALL",
    "DZD",
    "ARS",
    "AMD",
    "AUD",
    "AZN",
    "BHD",
    "BDT",
    "BYN",
    "BZD",
    "BOB",
    "BAM",
    "BWP",
    "BRL",
    "GBP",
    "BND",
    "BGN",
    "BIF",
    "KHR",
    "CAD",
    "CVE",
    "XAF",
    "CLP",
    "CNY",
    "COP",
    "KMF",
    "CDF",
    "CRC",
    "HRK",
    "CZK",
    "DKK",
    "DJF",
    "DOP",
    "EGP",
    "ERN",
    "EEK",
    "ETB",
    "EUR",
    "GEL",
    "GHS",
    "GTQ",
    "GNF",
    "HNL",
    "HKD",
    "HUF",
    "ISK",
    "IDR",
    "IRR",
    "IQD",
    "ILS",
    "JMD",
    "JPY",
    "JOD",
    "KZT",
    "KES",
    "KWD",
    "LVL",
    "LBP",
    "LYD",
    "LTL",
    "MOP",
    "MKD",
    "MGA",
    "MYR",
    "MUR",
    "MXN",
    "MDL",
    "MAD",
    "MZN",
    "MMK",
    "NAD",
    "NPR",
    "TWD",
    "NZD",
    "NIO",
    "NGN",
    "NOK",
    "OMR",
    "PKR",
    "PAB",
    "PYG",
    "PEN",
    "PHP",
    "PLN",
    "QAR",
    "RON",
    "RUB",
    "RWF",
    "SAR",
    "RSD",
    "SGD",
    "SOS",
    "ZAR",
    "KRW",
    "LKR",
    "SDG",
    "SEK",
    "CHF",
    "SYP",
    "TZS",
    "THB",
    "TOP",
    "TTD",
    "TND",
    "TRY",
    "UGX",
    "UAH",
    "AED",
    "UYU",
    "UZS",
    "VEF",
    "VND",
    "XOF",
    "YER",
    "ZMK",
    "ZWL"
]

export const CURRENCY_SYMBOLS: Record<string, string> = {
    "INR": "₹",
    "USD": "$",
    "AFN": "؋",
    "ALL": "L",
    "DZD": "د.ج",
    "ARS": "$",
    "AMD": "֏",
    "AUD": "$",
    "AZN": "₼",
    "BHD": "ب.د",
    "BDT": "৳",
    "BYN": "Br",
    "BZD": "BZ$",
    "BOB": "Bs.",
    "BAM": "KM",
    "BWP": "P",
    "BRL": "R$",
    "GBP": "£",
    "BND": "$",
    "BGN": "лв",
    "BIF": "FBu",
    "KHR": "៛",
    "CAD": "$",
    "CVE": "$",
    "XAF": "FCFA",
    "CLP": "$",
    "CNY": "¥",
    "COP": "$",
    "KMF": "CF",
    "CDF": "FC",
    "CRC": "₡",
    "HRK": "kn",
    "CZK": "Kč",
    "DKK": "kr",
    "DJF": "Fdj",
    "DOP": "RD$",
    "EGP": "£",
    "ERN": "Nfk",
    "EEK": "kr",
    "ETB": "Br",
    "EUR": "€",
    "GEL": "₾",
    "GHS": "₵",
    "GTQ": "Q",
    "GNF": "FG",
    "HNL": "L",
    "HKD": "HK$",
    "HUF": "Ft",
    "ISK": "kr",
    "IDR": "Rp",
    "IRR": "﷼",
    "IQD": "ع.د",
    "ILS": "₪",
    "JMD": "J$",
    "JPY": "¥",
    "JOD": "د.ا",
    "KZT": "₸",
    "KES": "KSh",
    "KWD": "د.ك",
    "LVL": "Ls",
    "LBP": "ل.ل",
    "LYD": "ل.د",
    "LTL": "Lt",
    "MOP": "MOP$",
    "MKD": "ден",
    "MGA": "Ar",
    "MYR": "RM",
    "MUR": "₨",
    "MXN": "$",
    "MDL": "lei",
    "MAD": "د.م.",
    "MZN": "MT",
    "MMK": "Ks",
    "NAD": "$",
    "NPR": "₨",
    "TWD": "NT$",
    "NZD": "$",
    "NIO": "C$",
    "NGN": "₦",
    "NOK": "kr",
    "OMR": "ر.ع.",
    "PKR": "₨",
    "PAB": "B/.",
    "PYG": "₲",
    "PEN": "S/",
    "PHP": "₱",
    "PLN": "zł",
    "QAR": "ر.ق",
    "RON": "lei",
    "RUB": "₽",
    "RWF": "RF",
    "SAR": "ر.س",
    "RSD": "дин.",
    "SGD": "$",
    "SOS": "S",
    "ZAR": "R",
    "KRW": "₩",
    "LKR": "₨",
    "SDG": "ج.س.",
    "SEK": "kr",
    "CHF": "CHF",
    "SYP": "£",
    "TZS": "TSh",
    "THB": "฿",
    "TOP": "T$",
    "TTD": "TT$",
    "TND": "د.ت",
    "TRY": "₺",
    "UGX": "USh",
    "UAH": "₴",
    "AED": "د.إ",
    "UYU": "$U",
    "UZS": "soʻm",
    "VEF": "Bs",
    "VND": "₫",
    "XOF": "CFA",
    "YER": "﷼",
    "ZMK": "ZK",
    "ZWL": "Z$"
};
